name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ] # Trigger on pushes to the main branch
jobs:
  deploy:
    runs-on: ubuntu-latest # Use the latest Ubuntu environment
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Verify package.json exists
      - name: Verify package.json exists
        run: |
          if [ ! -f package.json ]; then
            echo "package.json not found!"
            exit 1
          fi

      # Step 3: Set environment variables
      - name: Set environment variables
        run: |
          echo "FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" >> $GITHUB_ENV
          echo "FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" >> $GITHUB_ENV
          echo "FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}" >> $GITHUB_ENV

      # Step 4: Install dependencies including Firebase
      - name: Install dependencies
        run: |
          npm install
          npm install firebase

      # Step 5: Build the project
      - name: Build project
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        run: npm run build

      # Step 6: Deploy to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          publish_dir: ./build # Publish the build directory
