name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ] # Trigger on pushes to the main branch
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Use the latest Ubuntu environment
    permissions:
      contents: write
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Verify package.json exists
      - name: Verify package.json exists
        run: |
          if [ ! -f package.json ]; then
            echo "package.json not found!"
            exit 1
          fi

      # Step 3: Set environment variables
      - name: Set environment variables
        run: |
          echo "FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" >> $GITHUB_ENV
          echo "FIREBASE_PROJECT_ID=${{ secrets.FIREBASE_PROJECT_ID }}" >> $GITHUB_ENV
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> $GITHUB_ENV
          echo "SENDER_ID=${{ secrets.SENDER_ID }}" >> $GITHUB_ENV
          echo "FIREBASE_APP_ID=${{ secrets.FIREBASE_APP_ID }}" >> $GITHUB_ENV
          echo "MEASUREMENT_ID=${{ secrets.MEASUREMENT_ID }}" >> $GITHUB_ENV

      # Step 4: Install dependencies including Firebase
      - name: Install dependencies
        run: |
          npm install
          npm install firebase

      # Step 5: Build the project
      - name: Build project
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          SENDER_ID: ${{ secrets.SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          MEASUREMENT_ID: ${{ secrets.MEASUREMENT_ID }}
        run: npm run build

      # Step 6: Deploy to GitHub Pages
      - name: Deploy
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add build
          git commit -m "Deploy to GitHub Pagess"
          git push origin `git subtree split --prefix build main`:gh-pages --force
