name: Deploy to GitHub Pages
on:
  push:
    branches: [ main ] # Trigger on pushes to the main branch
jobs:
  deploy:
    runs-on: ubuntu-latest # Use the latest Ubuntu environment
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Replace placeholders in keys.js with secrets
      - name: Replace Firebase Config
        run: |
          sed -i "s/API_KEY_PLACEHOLDER/${{ secrets.FIREBASE_API_KEY }}/g" keys.js
          sed -i "s/PROJECT_ID_PLACEHOLDER/${{ secrets.FIREBASE_PROJECT_ID }}/g" keys.js
          sed -i "s/APP_ID_PLACEHOLDER/${{ secrets.FIREBASE_APP_ID }}/g" keys.js

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Install Firebase
        run: npm install firebase

      # Step 5: Build the project
      - name: Build project
        run: npm run build

      # Step 6: Deploy to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # Publish the build directory
